---
title: "reproduce"
author: "Shiyu Liu"
date: "12/15/2019"
output: pdf_document
---
```{r}
hold_out <- function(data){
  #Installing Caret Package
  library(caret)
  accuracy_list2 = c()
  for (j in 1:15){
    set.seed(j*10)
    #Data Partitioning
    trainIndices <- createDataPartition(y = data$class, p=0.3, list = FALSE)
    #trainIndices = sample(1:nrow(ecoli),nrow(ecoli)*0.8)
    trainset <- data[trainIndices, ]
    testset <- data[-trainIndices, ]
    
  #Naive Bayes Classifier
    # Installing e1071
    library(e1071)
    # Applying Naive Bayes
    nbc <- naiveBayes(class ~., data =trainset )
    # Making predictions
    prediction2 <- predict(nbc, testset, type="class")
    cm2 <- table(testset$class, prediction2, dnn = c("Real Values", "Predictions"))
    #Calculating Accuracy
    n2 = diag(cm2)
    accuracy2 <- sum(n2)/sum(cm2)
    accuracy_list2[j] = accuracy2
  }
  a2 = sum(accuracy_list2)/15
  return(a2)
}
```


```{r}
cross_validation_naive_bayes <- function(yourData, k){
  require(caret)
  set.seed(100)
  folds<-createFolds(y=yourData$class,k)
  accuracy_list2=c()
  #Perform k fold cross validation
  for(i in 1:k){
    #Segement your data by fold using the which() function 
    train_cv<-yourData[-folds[[i]],]
    test_cv<-yourData[folds[[i]],]
     #Naive Bayes Classifier
    # Installing e1071
    library(e1071)
    # Applying Naive Bayes
    nbc <- naiveBayes(class ~., data =train_cv )
    # Making predictions
    prediction2 <- predict(nbc, test_cv, type="class")
    cm2 <- table(test_cv$class, prediction2, dnn = c("Real Values", "Predictions"))
    #Calculating Accuracy
    n2 = diag(cm2)
    accuracy2 <- sum(n2)/sum(cm2)
    accuracy_list2[i] = accuracy2
  }
  return(accuracy_list2)
}
```

```{r}
standard_derivation <- function(data){
  s <- sum(data)/length(data)
  power_res <- 0
  for(i in 1:length(data)){
    power_res = power_res + (data[i]-s)*(data[i]-s)
  }
  res <- sqrt(power_res/length(data))
  return(res)
}
```

#soybean
```{r}
url= "https://archive.ics.uci.edu/ml/machine-learning-databases/soybean/soybean-large.data"
soybean <-  as.data.frame(read.table(file = url, header = FALSE, dec = ".", sep = ","))
#colnames(ecoli) <- c("Sequence Name", "mcg", "gvh", "lip", "chg", "aac", "alm1", "alm2","class")
colnames(soybean)[1] <- "class"
soybean
```

```{r}
k_fold_result = c()
cv_nbc_2 = cross_validation_naive_bayes(yourData=soybean, k=2)
k_fold_result[1] = sum(cv_nbc_2)/2
cv_nbc_5 = cross_validation_naive_bayes(yourData=soybean, k=5)
k_fold_result[2] = sum(cv_nbc_5)/5
cv_nbc_10 = cross_validation_naive_bayes(yourData=soybean, k=10)
k_fold_result[3] = sum(cv_nbc_10)/10
cv_nbc_20 = cross_validation_naive_bayes(yourData=soybean, k=20)
cv_nbc_20
k_fold_result[4] = sum(cv_nbc_20)/20
k_fold_result


hold_out_result = hold_out(data=soybean)
hold_out_result

sd <- standard_derivation(cv_nbc_5)
sd
```